# Generated by Django 3.0.6 on 2020-05-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_searchhistory_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='release_year',
            field=models.DecimalField(decimal_places=0, max_digits=4),
        ),
    ]
