# Generated by Django 3.0.6 on 2020-05-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.CharField(default='https://img.icons8.com/pastel-glyph/512/000000/user-male--v1.png', max_length=9999),
        ),
    ]
