# Generated by Django 3.0.6 on 2020-05-13 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200513_0926'),
        ('user', '0005_auto_20200513_1020'),
    ]

    operations = [
    ]
